twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'd F Y'
        timezone: 'Europe/Paris'

when@test:
    twig:
        strict_variables: true
