# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm # ou mongodb ou propel ou phpcr
    mappings:
        etudiant_image:
            uri_prefix: /images/etudiants
            upload_destination: '%kernel.project_dir%/public/images/etudiants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
