controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_tableau:

    path: /tableau/{status}/{year}

    defaults: { _controller: App\Controller\AdminController::tab, status: 'Tous', year: null }

    requirements:

        status: Entrepreneur|Tous|Formation|Employé|Stage|Chômeur

        year: \d+